openapi: 3.0.0
info:
  title: Wheelancer API with Swagger
  version: '1.0'
  description: "This is a simple CRUD API application made with Express and documented with Swagger 
    <br><br><h1>AUTH PASS (üîë): admin
    <br><br><h1>SUPER_AUTH PASS (üîëü¶π‚Äç‚ôÇÔ∏è): superadmin for System API calls and Admin registration."
servers:
  - url: http://wheelancer.hopto.org:3013/
  

#---<<<<<<<<<<<<<<<<<<<<<<<<<<<USER>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
    Super-Authorization:          
      type: apiKey
      name: super_auth
      in: header
      description: 'Super Special key for creating couriers => superadmin'  
  schemas:
    User: 
           type: object
           required: 
               - username
               - email
               - name
               - password
           properties:
               user_id:
                   type: integer
               username:
                   type: string
               name:
                   type: string
               email:
                   type: string
               biography:
                   type: string
               password:
                   type: string
           example:
               username: Mahmut_03
               email: test@test.com
               name: Mahmut
               password: testtset

         
security:
    - bearerAuth: []

paths:
#---<<<<<<<<<<<<<<<<<<<<<<<<<<<System>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  /system/inserttuples:
    post:
      security:
        - Super-Authorization: []
      tags:
        - "System"

      description: Insert example tuples.
      responses:
        '200':
          description: OK - Inserted
        '500':
          description: MYSQL ERROR.

  /system/truncatetables:
    delete:
      security:
        - Super-Authorization: []
      tags:
        - "System"

      description: Truncate tables.
      responses:
        '200':
          description: OK - Truncated.
        '500':
          description: MYSQL ERROR.

  /system/inserttables:
    post:
      security:
        - Super-Authorization: []
      tags:
        - "System"

      description: <h1>Creates tables (Do not use until fully implemented)üß∞.
      responses:
        '200':
          description: OK - Inserted.
        '500':
          description: MYSQL ERROR.


#---<<<<<<<<<<<<<<<<<<<<<<<<<<<USER>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  /user/checktoken:
    post:
      tags:
        - "User-General"

      description: Only checks token for persistent login.
              
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error

  /user/login:
    post:
      tags:
        - "User-General"

      description: Performs login operation and give user JWT token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                  email:
                    type: string
                  password:
                    type: string
              example:
               email: Mahmut_03
               password: testtset
              
      responses:
        '200':
          description: OK - Successfully logged in.
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                  name:
                    type: string
                  surname:
                    type: string
                  birthday:
                    type: string
                  idnum:
                    type: string
                  balance:
                    type: integer
                  email:
                    type: string
                  password:
                    type: string
                  registration_date:
                    type: string
                  type:
                    type: integer
                  token:
                    type: string
        '401':
          description: Wrong credentials.

  /user/register:
    post:        
      tags:
        - "User-General"

      description: Registers the user. Super-Auth Key is required in order to register as Admin.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                birthday:
                  type: string
                idnum:
                  type: string
                email:
                  type: string
                password:
                  type: string
                type:
                  type: integer
              example:
                name: John
                surname: asdasd
                birthday: "2022-05-01T20:41:21.457Z"
                idnum: "123131323"
                email: test@wheeasdasdasdlancer.com
                password: testtset
                type: 0
      responses:
        '200':
          description: OK - Successfully registered.
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  surname:
                    type: string
                  birthday:
                    type: string
                  idnum:
                    type: string
                  email:
                    type: string
                  password:
                    type: string
                  type:
                    type: integer
                  token:
                    type: string
        '406':
          description: Not Acceptable - User with same username or email already exists.

  /user/sendverification:
    post:        
      tags:
        - "User-General"

      description: Send mail verificaiton for users.
      
      responses:
        '200':
          description: Mail sent, please check your mailbox.
        '409':
          description: User is already verified.
        '429':
          description: User requested verification code more than 5 times. Please try again in 10 minutes.
        '500':
          description: Could not send verification code.
          
  /user/checkverification:
    post:        
      tags:
        - "User-General"

      description: Checks requested verification code to verify user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  example: "6208"
          
      responses:
        '200':
          description: Successfully verified.
        '401':
          description: Please send a verification code.
        '403':
          description: Wrong verification code.
        '408':
          description: Verification code expired.
        '409':
          description: User is already verified.
        '429':
          description: Has made too many wrong entry please request a new code.
        '500':
          description: Interval Server Error

  /user/addbalance:
    put:
      security:
        - bearerAuth: []
      tags:
        - "User-General"

      description: Adds a specific amount to user's wallet.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                  amount:
                    type: number
                    format: amount
                    example: 100
      responses:
        '200':
          description: OK - Balance added to your account.
        '500':
          description: Interval Server Error

  
  /user/getmyuser:
    get:
      security:
        - bearerAuth: []
      tags:
        - "User-General"

      description: Gets user info from token.
      responses:
        '200':
          description: OK - Successfully listed.
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    user_id:
                      type: integer
                    name:
                      type: string
                    surname:
                      type: string
                    birthday:
                      type: string
                    id_num:
                      type: string
                    balance:
                      type: integer
                    email:
                      type: string
                    password:
                      type: string
                    email_verified:
                      type: integer
                    registration_date:
                      type: string
                    verify_try:
                      type: integer
                    verifier_id:
                      type: integer
                    avg_rating:
                      type: number
                    is_verified:
                      type: integer
                    type:
                      type: integer
        '500':
          description: Interval Server Error

#---<<<<<<<<<<<<<<<<<<<<<<<<<<<ADMIN>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  /user/getunverifiedcouriers:
    get:
      security:
        - bearerAuth: []
      tags:
        - "User-Admin"

      description: Gets unverified couriers for admin.
      responses:
        '200':
          description: OK - Successfully listed.
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    user_id:
                      type: integer
                    name:
                      type: string
                    surname:
                      type: string
                    birthday:
                      type: string
                    id_num:
                      type: string
                    balance:
                      type: integer
                    email:
                      type: string
                    password:
                      type: string
                    email_verified:
                      type: integer
                    registration_date:
                      type: string
                    verify_try:
                      type: integer
                    verifier_id:
                      type: integer
                    avg_rating:
                      type: number
                    is_verified:
                      type: integer
        '401':
          description: You do not have permission to do that.


  /user/getverifiedcouriers:
    get:
      security:
        - bearerAuth: []
      tags:
        - "User-Admin"

      description: Gets verified Couriers
      parameters:
        - in: query
          name: uid
          schema:
            type: integer
          description: Id of user
          example: 1
      responses:
        '200':
          description: OK - Successfully listed.
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    user_id:
                      type: integer
                    user_name:
                      type: string
                    name:
                      type: string
                    email:
                      type: string
                    biography:
                      type: string   
        '401':
          description: Unauthorized - Token is expired or wrong.

  /user/verifycourier:
    put:
      security:
        - bearerAuth: []
      tags:
        - "User-Admin"
      description: For verifying the courier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                  courier_id:
                    type: integer
                    format: courier_id
                    example: 3
      responses:
        '200':
          description: OK - Successfully verified.
        '401':
          description: Unauthorized - You do not have permission to do that.

#---<<<<<<<<<<<<<<<<<<<<<<<<<<<COURIER>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  /user/addvehicle:
    post:
      security:
        - bearerAuth: []
        
      tags:
        - "User-Courier"

      description: Add vehicle to courier.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                model:
                  type: string
                brand:
                  type: string
                max_length:
                  type: number
                max_width:
                  type: number
                max_height:
                  type: number
                max_weight:
                  type: number
                horsepower:
                  type: integer
                registration_plate:
                  type: string
                type:
                  type: string
              example:
                model: Golf,
                brand: Volkswagen
                max_length: 120.000
                max_width: 90.000
                max_height: 80.000
                max_weight: 40.000
                horsepower: 120
                registration_plate: 06MS8967
                type: Sedan
                
      responses:
        '200':
          description: OK - Vehicle successfully added.
        '401':
          description: Unauthorized - User must be courier.
        '500':
          description: Internal Server Error
          
          
  /user/myvehicles:
    get:
      security:
        - bearerAuth: []
      tags:
        - "User-Courier"

      description: Returns courier's vehicles
      responses:
        '200':
          description: OK - Listed
          content:
            application/json:
              schema:
                type: array
                items:
                    properties:
                      vehicle_id:
                        type: integer
                      user_id:
                        type: integer
                      model:
                        type: string
                      brand:
                        type: string
                      max_length:
                        type: number
                      max_width:
                        type: number
                      max_height:
                        type: number
                      max_weight:
                        type: number
                      horsepower:
                        type: integer
                      registration_plate:
                        type: string
                      type:
                        type: string
                      
        '500':
          description: Interval Server Error
          
  /user/adddocument:
    post:
      security:
        - bearerAuth: []
        
      tags:
        - "User-Courier"

      description: Adds document to the courier to be verified.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                document:
                  type: string
                  format: binary
              
      responses:
        '200':
          description: OK - Document added successfully.
        '402':
          description: Document could not be added.
        '500':
          description: Internal Server Error
          
  /user/mydocument:
    get:
      security:
        - bearerAuth: []
      tags:
        - "User-Courier"

      description: Gets document data for courier.
      responses:
        '200':
          description: OK
          content:
            image/png:
              schema: 
                type: string
                format: binary
        '404':
          description: Document could not be found.
        '405':
          description: Document file is missing in our system.
        '500':
          description: Internal Server Error
          
  /transport/pickupcargo:
    post:
      security:
        - bearerAuth: []
        
      tags:
        - "User-Courier"

      description: Picking up package for courier.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                package_id:
                  type: integer
              example:
                package_id: 1
                
      responses:
        '200':
          description: OK - Package successfully picked up.
        '401':
          description: You do not have permission to perform this.<br>OR<br>You do not have permission to pickup this package.<br>OR<br>This package cannot be picked up at the moment.
        '407':
          description: Package could not be picked up.
        '500':
          description: Internal Server Error
          
  /transport/deliverpackage:
    post:
      security:
        - bearerAuth: []
        
      tags:
        - "User-Courier"

      description: Delivering package for courier with sending photo and verification mail for receiver.
                
      responses:
        '200':
          description: OK - Package delivery successfully reported.
        '401':
          description: You do not have permission to perform this.<br>OR<br>You do not have permission to deliver this package.<br>OR<br>This package cannot be delivered at the moment.
        '407':
          description: Package delivery confirm mail failed to sent.<br>OR<br>Package delivery could not be reported.
        '408':
          description: Package delivery proof could not be added.
        '500':
          description: Internal Server Error
          
  /transport/confirmdelivery:
    get:
      security:
        - bearerAuth: []
      tags:
        - "User-Courier"

      description: Confirming delivery from  receiver via url
      responses:
        '200':
          description: OK - Listed
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    tid:
                      type: string
                    customer_id:
                      type: integer
                    courier_id:
                      type: integer
                    cargo_size:
                      type: integer
                    cargo_weight:
                      type: integer
                    creation_date:
                      type: string
                    departure_cords:
                      type: string
                    arrival_cords:
                      type: string
                      
        '401':
          description: Unauthorized - Token is expired or wrong.
          
  /transport/addoffer:
    post:
      security:
        - bearerAuth: []
        
      tags:
        - "User-Courier"

      description: Courier creates an offer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                package_id:
                  type: integer
                transport_id:
                  type: integer
                price:
                  type: number
              example:
                package_id: 1
                transport_id: 2
                price: 57.50
      responses:
        '200':
          description: OK - Offer successfully sent.
        '400':
          description: Offer could not be sent.
        '401':
          description: User must be courier.
        '412':
          description: Selected package could not found.<br>OR<br>New cargo does not fit your vehicle.<br>OR<br>New cargo exceeds maximum weight capacity of your vehicle.
        '413':
          description: Selected travel does not have a vehicle.
        '500':
          description: Internal Server Error
          
  /transport/add:
    post:
      security:
        - bearerAuth: []
        
      tags:
        - "User-Courier"

      description: Courier creates a transport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                vehicle_id:
                  type: integer
                courier_pos_long:
                  type: number
                courier_pos_lat:
                  type: number
                departure_date:
                  type: string
                arrival_date:
                  type: string
              example:
                vehicle_id: 1
                courier_pos_long: 43.894165
                courier_pos_lat: 57.181412
                departure_date: "2022-05-05"
                arrival_date: "2022-05-08"
      responses:
        '200':
          description: OK - Transport successfully added.
        '401':
          description: User must be courier.
        '404':
          description: Vehicle could not be found.
        '407':
          description: Transport could not added.
        '500':
          description: Internal Server Error
          
  /transport/getcouriertransports:
    get:
      security:
        - bearerAuth: []
      tags:
        - "User-Courier"

      description: Gets Courier's all transports
      responses:
        '200':
          description: OK - Listed
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    transport_id:
                      type: string
                    courier_id:
                      type: integer
                    vehicle_id:
                      type: integer
                    courier_pos_long:
                      type: number
                    courier_pos_lat:
                      type: number
                    last_update_date:
                      type: string
                    remaining_weight:
                      type: number
                    remaining_volume:
                      type: number
                    departure_date:
                      type: integer
                    arrival_date:
                      type: integer
                    status:
                      type: string
                    model:
                      type: string
                    brand:
                      type: string
                    max_length:
                      type: number
                    max_width:
                      type: number
                    max_height:
                      type: number
                    max_weight:
                      type: number
                    horsepower:
                      type: integer
                    registration_plate:
                      type: string
                    type:
                      type: string
                      
        '401':
          description: User must be courier.
        '500':
          description: Internal Server Error
          
  /user/myfeedbacks:
    get:
      security:
        - bearerAuth: []
      tags:
        - "User-Courier"

      description: Gets all feedback data for courier.
      responses:
        '200':
          description: OK - Listed
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    courier_id:
                      type: integer
                    customer_id:
                      type: integer
                    pid:
                      type: integer
                    message:
                      type: string
                    rate:
                      type: number
                    date:
                      type: string
                    name:
                      type: string
                    surname:
                      type: string
                    registration_date:
                      type: string
                      
        '401':
          description: User must be courier.
        '500':
          description: Internal Server Error

#---<<<<<<<<<<<<<<<<<<<<<<<<<<<TRANSPORT>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  /transport/alltransports:
    get:
      security:
        - bearerAuth: []
      tags:
        - "Transport"

      description: Listing All Transports
      responses:
        '200':
          description: OK - Listed
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    tid:
                      type: string
                    customer_id:
                      type: integer
                    courier_id:
                      type: integer
                    cargo_size:
                      type: integer
                    cargo_weight:
                      type: integer
                    creation_date:
                      type: string
                    departure_cords:
                      type: string
                    arrival_cords:
                      type: string
                      
        '401':
          description: Unauthorized - Token is expired or wrong.
          
  /transport/nearpackages:
    get:
      security:
        - bearerAuth: []
      tags:
        - "User-Courier"

      description: Brings near packages to the courier.
      parameters:
        - in: query
          name: s_city
          schema:
            type: string
          description: Departure City
          example: Ankara
        - in: query
          name: curr_pos_long
          schema:
            type: number
          description: Longitude of the current courier position
          example: 126.574000
        - in: query
          name: curr_pos_lat
          schema:
            type: number
          description: Latitude of the current courier position
          example: 354.153500
        - in: query
          name: radius
          schema:
            type: number
          description: (In Meters)
          example: 5
      responses:
        '200':
          description: OK - Listed
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    pid:
                      type: integer
                    cid:
                      type: integer
                    transport_id:
                      type: integer
                    length:
                      type: number
                    width:
                      type: number
                    height:
                      type: number
                    weight:
                      type: number
                    type:
                      type: string
                    s_long:
                      type: number
                    s_lat:
                      type: number
                    d_long:
                      type: number
                    d_lat:
                      type: number
                    status:
                      type: string
                    receiver_fullname:
                      type: string
                    receiver_email:
                      type: string
                    estimated_delivery_date:
                      type: string
                    chat_channel_id:
                      type: string
                    s_city:
                      type: string
                    d_city:
                      type: string
                      
        '401':
          description: You do not have permission to perform this.
          
  /transport/showoffers:
    get:
      security:
        - bearerAuth: []
      tags:
        - "Transport"

      description: Gets all offers detailed for couriers, minimal for customers
      
      responses:
        '200':
          description: OK - Listed
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    accept_status:
                      type: string
                    pid:
                      type: integer
                    courier_id:
                      type: integer
                    transport_id:
                      type: integer
                    price:
                      type: number
                    avg_rating:
                      type: number
                    registration_date:
                      type: string
                    vehicle_id:
                      type: integer
                    model:
                      type: string
                    brand:
                      type: string
                    max_length:
                      type: number
                    max_width:
                      type: number
                    max_height:
                      type: number
                    max_weight:
                      type: number
                    horsepower:
                      type: integer
                    registration_plate:
                      type: string
                    courier_full_name:
                      type: string
                      
        '401':
          description: You do not have permission to perform this.
          
  /transport/currentposition:
    put:
      security:
        - bearerAuth: []
      tags:
        - "Transport"

      description: Update courier's current position.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                  curr_long:
                    type: number
                    format: curr_long
                    example: 39.874567
                  curr_lat:
                    type: number
                    format: curr_lat
                    example: 42.874867
      responses:
        '200':
          description: OK - Courier's current position updated in all transports.
        '401':
          description: Unauthorized - User must be courier.
        '500':
          description: Interval Server Error

#---<<<<<<<<<<<<<<<<<<<<<<<<<<<CUSTOMER>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  /transport/mytransports:
    get:
      security:
        - bearerAuth: []
      tags:
        - "User-Customer"
      description: Listing customer's transports
      parameters:
        - in: query
          name: uid
          schema:
            type: integer
          description: Id of user
          example: 1
      responses:
        '200':
          description: OK - Listed
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    tid:
                      type: string
                    customer_id:
                      type: integer
                    courier_id:
                      type: integer
                    cargo_size:
                      type: integer
                    cargo_weight:
                      type: integer
                    creation_date:
                      type: string
                    departure_cords:
                      type: string
                    arrival_cords:
                      type: string
                      
        '401':
          description: Unauthorized - Token is expired or wrong.
          
  /transport/getcourierlocation:
    get:
      security:
        - bearerAuth: []
      tags:
        - "User-Customer"
      description: Gets courier's current location to a customer.
      parameters:
        - in: query
          name: package_id
          schema:
            type: integer
          description: Id of the package
          example: 1
      responses:
        '200':
          description: OK - Listed
          content:
            application/json:
              schema:
                type: object
                properties:
                  courier_pos_long:
                    type: string
                  courier_pos_lat:
                    type: integer
                  last_update_date:
                    type: integer
                      
        '401':
          description: Unauthorized - You need to be a customer.
          
  /transport/acceptoffer:
    post:
      security:
        - bearerAuth: []
        
      tags:
        - "User-Customer"

      description: Accepts courier's offer for customer.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                package_id:
                  type: integer
                transport_id:
                  type: integer
                courier_id:
                  type: integer
              example:
                package_id: 12
                transport_id: 14
                courier_id: 5
                
      responses:
        '200':
          description: OK - Offer accepted.
        '401':
          description: You do not have permission to perform this.<br>OR<br>You do not own this package.<br>OR<br>Courier did not send offer for this package.<br>OR<br>You already have accepted an offer for this package.
        '407':
          description: Offer could not be accepted.
        '412':
          description: You do not have enough balance to accept this offer.
        '500':
          description: Internal Server Error
          
  /transport/canceloffer:
    delete:
      security:
        - Super-Authorization: []
      tags:
        - "User-Customer"

      description: Remove offer if status = CREATED, NEGOTIATED for courier |  status = CREATED for customer
      parameters:
        - in: query
          name: package_id
          schema:
            type: integer
          description: Id of the package
          example: 1
        - in: query
          name: transport_id
          schema:
            type: integer
          description: Id of transportation
          example: 2
      responses:
        '200':
          description: OK - Offer has been cancelled.
        '404':
          description: Offer could not be found.
        '406':
          description: Offer cannot be removed after negotiation.<br>OR<br>Offer cannot be removed after picking up.
        '409':
          description: Package details could not be altered.<br>OR<br>Offer could not be cancelled.
        '500':
          description: Internal Server Error
          
  /user/givefeedback:
    post:
      security:
        - bearerAuth: []
        
      tags:
        - "User-Customer"

      description: Give feedback to a courier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                courier_id:
                  type: integer
                package_id:
                  type: integer
                message:
                  type: string
                rate:
                  type: number
              example:
                courier_id: 12
                package_id: 14
                message: Neat
                rate: 4.2
                
      responses:
        '200':
          description: Feedback successfully given.
        '401':
          description: User must be customer.
        '404':
          description: Package could not found.
        '407':
          description: Courier avg score could not be updated.
        '409':
          description: Feedback could not given probably already given.
        '412':
          description: Package should be at least picked up from courier in order to give a feedback.
        '500':
          description: Internal Server Error
          
#---<<<<<<<<<<<<<<<<<<<<<<<<<<<Package>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  /package/customerpackages:
    get:
      security:
        - bearerAuth: []
        
      tags:
        - "Package"

      description: Gets customer's own packages return all of them
      
      responses:
        '200':
          description: OK - Successfully registered.
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    pid:
                      type: integer
                    cid:
                      type: integer
                    transport_id:
                      type: integer
                    length:
                      type: number
                    width:
                      type: number
                    height:
                      type: number
                    weight:
                      type: number
                    type:
                      type: string
                    s_long:
                      type: number
                    s_lat:
                      type: number
                    d_long:
                      type: number
                    d_lat:
                      type: number
                    status:
                      type: string
                    receiver_email:
                      type: string
                    estimated_delivery_date:
                      type: string
                    chat_channel_id:
                      type: string
                    s_city:
                      type: string
                    d_city:
                      type: string
        '406':
          description: Not Acceptable - User with same username or email already exists.
        '500':
          description: Internal Server Error
          
  /package/customerpackage:
    get:
      security:
        - bearerAuth: []
      tags:
        - "Package"

      description: Gets customer's own package
      
      parameters:
        - in: query
          name: package_id
          schema:
            type: integer
          description: Id of the package
          example: 1
      
      responses:
        '200':
          description: OK - Successfully registered.
          content:
            application/json:
              schema:
                type: object
                properties:
                  pid:
                    type: integer
                  cid:
                    type: integer
                  transport_id:
                    type: integer
                  length:
                    type: number
                  width:
                    type: number
                  height:
                    type: number
                  weight:
                    type: number
                  type:
                    type: string
                  s_long:
                    type: number
                  s_lat:
                    type: number
                  d_long:
                    type: number
                  d_lat:
                    type: number
                  status:
                    type: string
                  receiver_email:
                    type: string
                  estimated_delivery_date:
                    type: string
                  chat_channel_id:
                    type: string
                  s_city:
                    type: string
                  d_city:
                    type: string
        '404':
          description: Package could not found.
        '500':
          description: Internal Server Error
          
    delete:
      security:
        - Super-Authorization: []
      tags:
        - "Package"

      description: Deletes customer's package to the system.
      parameters:
        - in: query
          name: package_id
          schema:
            type: integer
          description: Id of the package
          example: 1
      responses:
        '200':
          description: OK - Package successfully removed from system.
        '403':
          description: Package could not removed from system.
        '404':
          description: Package could not be found.
        '409':
          description: Package has an active transportation process you can not remove it from the system.
        '500':
          description: Internal Server Error
          
  /package/addcustomerpackage:
    post:
      security:
        - bearerAuth: []
        
      tags:
        - "Package"

      description: Add customer's package to the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                length:
                  type: number
                width:
                  type: number
                height:
                  type: number
                weight:
                  type: number
                type:
                  type: string
                s_long:
                  type: number
                s_lat:
                  type: number
                d_long:
                  type: number
                d_lat:
                  type: number
                receiver_email:
                  type: string
                s_city:
                  type: string
                d_city:
                  type: string
                receiver_fullname:
                  type: string
              example:
                length: 12.5
                width: 14.2
                height: 5.1
                weight: 12.4
                type: Flammable,Oxidizing
                s_long: -99.79118
                s_lat: 17.08936
                d_long: -91.79118
                d_lat: 19.08936
                receiver_email: ""
                s_city: ""
                d_city : ""
                receiver_fullname: Maruf Satir
                
      responses:
        '200':
          description: OK - Package added successfully.
        '403':
          description: Forbidden - Package could not be added.
        '500':
          description: Internal Server Error
  
  /package/allpackageproofs:
    get:
      security:
        - bearerAuth: []
        
      tags:
        - "Package"

      description: This works for both customer and courier.
      
      parameters:
        - in: query
          name: package_id
          schema:
            type: integer
          description: Id of the package
          example: 1
      
      responses:
        '200':
          description: OK - Successfully registered.
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    proof_id:
                      type: integer
                    pid:
                      type: integer
                    type:
                      type: string
                    image:
                      type: string
                    date:
                      type: string
        '500':
          description: Internal Server Error
          
          
  /package/packageproof:
    get:
      security:
        - bearerAuth: []
        
      tags:
        - "Package"

      description: Get Package Proof Data
      
      parameters:
        - in: query
          name: image_uuid
          schema:
            type: integer
          description: Id of the image
          example: 1
      
      responses:
        '200':
          description: OK - Successfully registered.
          content:
            image/png:
              schema: 
                type: string
                format: binary
        '404':
          description: Proof image could not found.
        '405':
          description: Image file is missing in our system.
        '500':
          description: Internal Server Error